Remove the Unicode BOM, if present. (#97)
swiftcsv/SwiftCSV pull request #103
Opened 2022-08-02 07:38 UTC by lardieri

CSV files saved by Excel and Airtable include the BOM when encoding to UTF-8.

2022-08-03 10:57 UTC, DivineDominion requested changes
LGTM, but I personally would prefer a change to the "`bom`" constant to make its meaning more obvious.

Unrelated to that, WDYT about merging your 0.6.2 fixes with this repo, too, so we can release that to CocoaPods proper>?

2022-08-03 10:57 UTC, DivineDominion commented on SwiftCSV/CSV.swift
> +fileprivate let bom = "\u{FEFF}"
I'd like to suggest two changes here:

1) Spell out `byteOrderMark` to make obvious what "bom" is supposed to mean and help other devs google the term;
2) Add a doc comment with a link to https://github.com/swiftcsv/SwiftCSV/issues/97, and/or copy parts your own super useful explanation (thanks for that!) from there.

2022-08-03 10:57 UTC, DivineDominion commented on SwiftCSVTests/utf8_with_bom.csv
> +12345,Heizölrückstoßabdämpfung,"€ 100,00",2
:) Thanks for that example -- and the test

2022-08-03 20:58 UTC, lardieri commented
I've added additional documentation around the BOM.

I'm happy to submit 0.6.2 for release, but you will need to create a branch in your repo for me to open PR against, since it forks from a previous point (039cc273).

2022-08-04 08:44 UTC, DivineDominion approved these changes
LGTM 👍 Thanks for the doc comment!

2022-08-04 08:49 UTC, DivineDominion commented
I've opened the branch `v0.6`. On top of the v0.6.1 release, it includes delimiter guessing, which was compatible with the v0.6 code. Will that be causing any trouble? Happy to discuss in another PR! :)

2022-08-04 08:49 UTC, merged

2022-08-04 08:50 UTC, DivineDominion commented
Also, thanks a lot for contributing to SwiftCSV! We've invited you to join the SwiftCSV GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/SwiftCSV/SwiftCSV/blob/master/CONTRIBUTING.md).