#95 ignore white spaces before and after quotes/fields/values
swiftcsv/SwiftCSV pull request #96
Opened 2021-08-07 05:28 UTC by ondrej-kvasnovsky

2021-08-12 18:23 UTC, DivineDominion requested changes
Looks good so far, thanks for adding the test case and providing a fix!

Would be great if you could add unit tests for other whitespace characters that should be skipped, too. Tabs come to mind; more exotic spaces like the non-breaking space (⌥+space on some keyboard layouts) would be optional "stretch goals" :)

2021-08-12 18:23 UTC, DivineDominion commented on SwiftCSVTests/CSVTests.swift
> +    func testInit_ParseFileWithQuotesAndSpaces() {
Since the implementation checks for `isWhitespace`, could you add similar-looking test cases for other whitespace characters, too?

2021-08-13 17:03 UTC, ondrej-kvasnovsky commented
> Looks good so far, thanks for adding the test case and providing a fix!
> 
> Would be great if you could add unit tests for other whitespace characters that should be skipped, too. Tabs come to mind; more exotic spaces like the non-breaking space (⌥+space on some keyboard layouts) would be optional "stretch goals" :)

Ok ok. Added more test data (using https://developer.apple.com/documentation/swift/character/3127019-iswhitespace). That that is pretty much the intent of this PR.

2021-08-20 08:37 UTC, DivineDominion approved these changes
Thanks!

2021-08-20 08:37 UTC, merged

2021-08-20 08:54 UTC, DivineDominion commented
We've invited you to join the SwiftCSV GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/SwiftCSV/SwiftCSV/blob/master/CONTRIBUTING.md).